AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.example::aws-lamda
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  CoursesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Courses
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AwsLamdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: target/aws-lamda-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref CoursesTable
          COGNITO_USER_POOL_ID: us-east-1_x2cp3uOn9
          COGNITO_CLIENT_ID: 49pajvflttmrub5glgeed22bd3
          FRONTEND_URL: "https://podiweda.com,https://www.podiweda.com"
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref CoursesTable
        - DynamoDBCrudPolicy:
            TableName: Tasks
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      BuildMethod: makefile

Outputs:
  AwsLamdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/courses'
  CoursesTableName:
    Description: DynamoDB table name
    Value: !Ref CoursesTable
